### ISSUE TITLE
Coin & ItemShop

### ISSUE THREAD

**Issue by steadfastree** [DevKor-github/reafy-back#5]
코인으로 아이템 구매, 활성화하는 로직 구현.

1. 유저 아이디를 받아 item table에 저장되어 있는 아이템을 카테고리 별로 리스트화하여 반환 -> 아이템 리스트를 반환할 때, 해당 Item이 user_item에 있는지도 포함하여 반환
2. 유저가 구매한 아이템을 user_item 테이블에 저장 
3. 유저 아이디를 받아 각 카테고리 별로 현재 활성화된 아이템을 반환

**Comment by steadfastree** [comment]
카테고리 table 없애고, 그냥 item entity 내에서 column 형태로 관리하는 게 나을듯

**Comment by min010324** [comment]
작업 완료
